16:14:55:321 [main] INFO  utility.DatabaseConnection - Connection established
16:15:12:949 [main] INFO  utility.DatabaseConnection - Connection established
13:49:28:684 [main] INFO  utility.ConnectionPool - The connection was retrieved: com.mysql.cj.jdbc.ConnectionImpl@41e350f1
13:50:07:593 [main] INFO  utility.ConnectionPool - The connection was retrieved: com.mysql.cj.jdbc.ConnectionImpl@41e350f1
13:50:39:703 [main] INFO  utility.ConnectionPool - The connection was retrieved: com.mysql.cj.jdbc.ConnectionImpl@41e350f1
13:50:57:108 [main] INFO  utility.ConnectionPool - The connection was retrieved: com.mysql.cj.jdbc.ConnectionImpl@41e350f1
15:56:27:692 [main] ERROR main.Main - JAXBException occured
javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:269) ~[jaxb-api-2.4.0-b180830.0359.jar:2.3.0]
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:412) ~[jaxb-api-2.4.0-b180830.0359.jar:2.3.0]
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721) ~[jaxb-api-2.4.0-b180830.0359.jar:2.3.0]
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662) ~[jaxb-api-2.4.0-b180830.0359.jar:2.3.0]
	at jaxb.CarJAXB.marshall(CarJAXB.java:20) ~[classes/:?]
	at main.Main.main(Main.java:19) ~[classes/:?]
Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:122) ~[jaxb-api-2.4.0-b180830.0359.jar:2.3.0]
	at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:155) ~[jaxb-api-2.4.0-b180830.0359.jar:2.3.0]
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:267) ~[jaxb-api-2.4.0-b180830.0359.jar:2.3.0]
	... 5 more
